# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "degoogle" ]
  pull_request:
    branches: [ "degoogle" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.2' # Specify the Node.js version, or leave it as needed.
        
    - name: Install specific npm version
      run: npm install -g npm@8.1.2

    - name: Install dependencies
      run: npm run install:all

    - name: Building project
      run: npm run build:live
